"""empty message

Revision ID: 152f1975f039
Revises: 2d1afb6e2d86
Create Date: 2025-11-27 06:19:47.241398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152f1975f039'
down_revision = '2d1afb6e2d86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apartment_max_guests', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.drop_column('apartment_max_guests')

    # ### end Alembic commands ###
