"""empty message

Revision ID: 9290713b1ba2
Revises: 152f1975f039
Create Date: 2025-12-15 02:24:20.435591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9290713b1ba2'
down_revision = '152f1975f039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('g_profile_pic', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['google_id'])

    with op.batch_alter_table('saved_apartment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'apartment', ['apartment_id'], ['apartment_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('g_profile_pic', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('g_profile_pic')
        batch_op.drop_column('google_id')

    with op.batch_alter_table('saved_apartment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('g_profile_pic')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
