"""initial schema

Revision ID: 977ab3ddf161
Revises: 
Create Date: 2025-11-25 05:53:00.407278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977ab3ddf161'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apartment_user_id', sa.Integer(), nullable=False),
    sa.Column('booking_ref', sa.String(length=64), nullable=False),
    sa.Column('booking_apt_id', sa.Integer(), nullable=True),
    sa.Column('booking_checkin', sa.String(length=150), nullable=False),
    sa.Column('booking_checkout', sa.String(length=150), nullable=False),
    sa.Column('booking_guests', sa.Integer(), nullable=True),
    sa.Column('booking_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('booking_status', sa.Enum('active', 'inactive'), nullable=True),
    sa.Column('booking_date_created', sa.DateTime(), nullable=True),
    sa.Column('booking_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['booking_apt_id'], ['apartment.apartment_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_booking_ref'), ['booking_ref'], unique=True)

    op.create_table('payment',
    sa.Column('pay_id', sa.Integer(), nullable=False),
    sa.Column('pay_amt', sa.Float(), nullable=True),
    sa.Column('pay_user_id', sa.Integer(), nullable=False),
    sa.Column('pay_booking_id', sa.Integer(), nullable=True),
    sa.Column('pay_ref', sa.String(length=100), nullable=True),
    sa.Column('pay_method', sa.Enum('paystack', 'bank_transfer', 'debit_card', 'credit_card'), nullable=True),
    sa.Column('pay_status', sa.Enum('pending', 'failed', 'paid'), nullable=True),
    sa.Column('pay_data', sa.JSON(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pay_booking_id'], ['booking.booking_id'], ),
    sa.ForeignKeyConstraint(['pay_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('pay_id')
    )
    op.create_table('review',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_comment', sa.String(length=100), nullable=False),
    sa.Column('review_date_created', sa.DateTime(), nullable=True),
    sa.Column('review_user_id', sa.Integer(), nullable=False),
    sa.Column('review_apt_id', sa.Integer(), nullable=False),
    sa.Column('review_booking_id', sa.Integer(), nullable=False),
    sa.Column('review_rating_number', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['review_apt_id'], ['apartment.apartment_id'], ),
    sa.ForeignKeyConstraint(['review_booking_id'], ['booking.booking_id'], ),
    sa.ForeignKeyConstraint(['review_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('payment')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_booking_ref'))

    op.drop_table('booking')
    # ### end Alembic commands ###
